export const genres = {
    "Action": "action",
    "Adult Cast": "adult-cast",
    "Adventure": "adventure",
    "Anthropomorphic": "anthropomorphic",
    "Avant Garde": "avant-garde",
    "Boys Love": "shounen-ai",
    "Cars": "cars",
    "CGDCT": "cgdct",
    "Childcare": "childcare",
    "Comedy": "comedy",
    "Comic": "comic",
    "Crime": "crime",
    "Crossdressing": "crossdressing",
    "Delinquents": "delinquents",
    "Dementia": "dementia",
    "Demons": "demons",
    "Detective": "detective",
    "Drama": "drama",
    "Dub": "dub",
    "Ecchi": "ecchi",
    "Erotica": "erotica",
    "Family": "family",
    "Fantasy": "fantasy",
    "Gag Humor": "gag-humor",
    "Game": "game",
    "Gender Bender": "gender-bender",
    "Gore": "gore",
    "Gourmet": "gourmet",
    "Harem": "harem",
    "Hentai": "hentai",
    "High Stakes Game": "high-stakes-game",
    "Historical": "historical",
    "Horror": "horror",
    "Isekai": "isekai",
    "Iyashikei": "iyashikei",
    "Josei": "josei",
    "Kids": "kids",
    "Magic": "magic",
    "Magical Sex Shift": "magical-sex-shift",
    "Mahou Shoujo": "mahou-shoujo",
    "Martial Arts": "martial-arts",
    "Mecha": "mecha",
    "Medical": "medical",
    "Military": "military",
    "Music": "music",
    "Mystery": "mystery",
    "Mythology": "mythology",
    "Organized Crime": "organized-crime",
    "Parody": "parody",
    "Performing Arts": "performing-arts",
    "Pets": "pets",
    "Police": "police",
    "Psychological": "psychological",
    "Racing": "racing",
    "Reincarnation": "reincarnation",
    "Romance": "romance",
    "Romantic Subtext": "romantic-subtext",
    "Samurai": "samurai",
    "School": "school",
    "Sci-Fi": "sci-fi",
    "Seinen": "seinen",
    "Shoujo": "shoujo",
    "Shoujo Ai": "shoujo-ai",
    "Shounen": "shounen",
    "Showbiz": "showbiz",
    "Slice of Life": "slice-of-life",
    "Space": "space",
    "Sports": "sports",
    "Strategy Game": "strategy-game",
    "Super Power": "super-power",
    "Supernatural": "supernatural",
    "Survival": "survival",
    "Suspense": "suspense",
    "Team Sports": "team-sports",
    "Thriller": "thriller",
    "Time Travel": "time-travel",
    "Vampire": "vampire",
    "Video Game": "video-game",
    "Visual Arts": "visual-arts",
    "Work Life": "work-life",
    "Workplace": "workplace",
    "Yaoi": "yaoi",
    "Yuri": "yuri",
};